language: node_js
node_js:
- stable
sudo: false
cache: yarn

jobs:
  include:
  - stage: install
    script: yarn
    skip_cleanup: true
  - stage: test
    script: yarn test
    skip_cleanup: true
  - stage: release
    node_js: lts/*
    deploy:
      if: branch == master && !fork
      provider: script
      skip_cleanup: true
      script:
      - npx semantic-release