language: node_js
node_js:
- stable
sudo: true
cache: yarn

jobs:
  include:
    - stage: install
      script: yarn install
      skip_cleanup: true
    - stage: test
      script: yarn test
      skip_cleanup: true
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn global add semantic-release && semantic-release
        # if: branch = master