language: node_js

node_js:
- stable

jobs:
  include:
    - stage: install
      script: yarn
      skip_cleanup: true
    - stage: test
      script: yarn test
      skip_cleanup: true
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn run semantic-release
        # if: branch = master